(() => {
 const css=`.mouse-guide{position:fixed;left:22px;bottom:20px;z-index:170;max-width:min(340px,calc(100vw - 44px));padding:11px 15px;background:rgba(25,46,37,.66);border:1px solid #efddb842;border-radius:7px;backdrop-filter:blur(8px);color:#fff6e0;font:13px/1.65 SimSun,serif;letter-spacing:.04em;pointer-events:none;box-shadow:0 4px 18px #17332a20}.mouse-guide[hidden]{display:none}.mouse-guide b{color:#eed39a;font-weight:600;margin-right:8px}@media(max-width:650px){.mouse-guide{font-size:11px;bottom:12px;left:12px;max-width:210px;padding:8px 10px}}`;
 function addGuide(doc){const style=doc.createElement('style');style.textContent=css;doc.head.append(style);const g=doc.createElement('aside');g.className='mouse-guide';g.setAttribute('aria-label','操作提示');doc.body.append(g);return g;}
 const guide=addGuide(document);
 function rootHint(){const intro=document.querySelector('#prologue'),courtyard=document.querySelector('#courtyard'),hall=document.querySelector('#hall');const hide=(!intro.hidden)||!document.querySelector('#continuation')?.hidden||document.body.classList.contains('map-open');if(guide.hidden!==hide)guide.hidden=hide;let text='滚动鼠标走近山门，或点击「向前」';if(!courtyard.hidden)text='点击「沿石径」继续，滚轮控制入院画面';else if(!hall.hidden)text='静候天王依次点亮，观心诗句自动展开';else if(document.body.classList.contains('knock-ready'))text='将鼠标移到门环，轻点一下叩门';else if(window.scrollY>innerHeight*.8)text='点击一条心念，回应寺院的提问';guide.textContent='鼠标 · '+text;}
 new MutationObserver(rootHint).observe(document.body,{attributes:true,subtree:true,attributeFilter:['hidden','class']});window.addEventListener('scroll',rootHint,{passive:true});rootHint();
 const frame=document.querySelector('#continuation iframe');
 frame.addEventListener('load',()=>{try{const doc=frame.contentDocument;if(!doc?.body||frame.src==='about:blank')return;const g=addGuide(doc);const path=frame.src;function update(){let text='';const state=doc.body.dataset.state||'';if(path.includes('/wish/')){text=({arrival:'点击「走近许愿池」，或向下滚动',pickup:'点击铜钱，选择写下或说出心愿',choose:'点击「写下来」或「说出来」',writing:'输入心愿，再点击「收好这个愿」',voice:'点击开始说；也可切换为文字',binding:'心愿正在寄入铜钱，请稍候',ready:'拖动持币的手到光圈松开，或直接点击光圈',ending:'点击「继续往前」入殿，或「再寄一愿」'})[state]||'轻点池水寄愿，按提示继续';}else if(path.includes('/incense/')){text='点击选择心念；模拟感应点香，香燃后点击放入炉中';}else if(path.includes('/hall/')){text='滚动走向拜垫；轻按或长按合掌，向下滚动低头、向上起身。抽签时按住签筒左右摇';}else if(path.includes('/bodhi/')){text='滚动逐步观果，或等待自动展开；最后点击「存此一念」';}g.textContent='鼠标 · '+text;}
 update();new MutationObserver(update).observe(doc.body,{attributes:true,attributeFilter:['data-state']});}catch{}});
})();
