(() => {
 'use strict';
 const $=id=>document.getElementById(id), body=document.body;
 const panels=['opening','ritual','choices','writing','voice','back','coin','target','ending'];
 let submitting=false;
 let state='arrival',wishText='',drag=null,audio=null,muted=true,recognition=null,stream=null,meter=null,voiceEpoch=0,silenceTimer=null,inputTimer=null,noticeTimer=null,raf=null;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const delay=ms=>new Promise(resolve=>setTimeout(resolve,reduced?Math.min(ms,180):ms));
 function show(id,visible=true){$(id).hidden=!visible;}
 function hand(mode='point'){$('hand').className=mode; $('hand').firstElementChild.src=(mode==='holding'?'assets/holding-coin.png':`assets/${mode==='closed'?'closed-hand':'hand-point'}.webp`);}
 function setState(next,visible){state=next;body.dataset.state=next;panels.forEach(id=>show(id,visible.includes(id)));body.classList.remove('listening');hand();window.dispatchEvent(new CustomEvent('wishing-pool:state',{detail:{state:next}}));}
 function title(text,sub=''){$('ritualTitle').textContent=text;$('subtitle').textContent=sub;}
 function notice(text){clearTimeout(noticeTimer);$('notice').textContent=text;noticeTimer=setTimeout(()=>$('notice').textContent='',5500);}
 function steps(n){for(let i=1;i<=4;i++)$('step'+i).classList.toggle('active',i<=n);}
 function ripple(x=innerWidth*.5,y=innerHeight*.7,count=1){for(let i=0;i<count;i++){const ring=document.createElement('i');ring.className='ring';ring.style.cssText=`left:${x}px;top:${y}px;animation-delay:${i*.25}s`;$('ripples').append(ring);setTimeout(()=>ring.remove(),3600);}}
 function soundContext(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio;}
 function tone(freq,duration,type='sine',volume=.06){if(muted)return;const a=soundContext(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,a.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.6),a.currentTime+duration);g.gain.setValueAtTime(volume,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+duration);}
 let ambient=null;
 $('sound').onclick=()=>{muted=!muted;$('sound').setAttribute('aria-pressed',String(!muted));$('sound').setAttribute('aria-label',muted?'开启水声与投币音效':'关闭水声与投币音效');$('soundLabel').textContent=muted?'听水':'水声已起';if(!muted){tone(760,1.4);ambient=setInterval(()=>tone(400+Math.random()*600,.6,'sine',.012),2600);}else{clearInterval(ambient);}};
 function approach(){if(state!=='arrival')return;setState('pickup',['ritual','coin']);title('若心中有所愿，可投一枚。','这一池水，会替你收好。');$('hint').textContent='拾起铜钱，寄一枚心愿。';$('coinCaption').textContent='拾起一枚';$('coin').setAttribute('aria-label','拿起一枚铜钱');}
 $('approach').onclick=approach;
 window.addEventListener('wheel',e=>{if(e.deltaY>15)approach();},{passive:true});
 function pick(){setState('choose',['ritual','choices','coin']);title('这一枚，你想许给什么？');$('coinCaption').textContent='一枚铜钱，一份心愿';$('hint').textContent='不必斟酌，只需真心。';steps(1);tone(850,.8);$('write').focus({preventScroll:true});}
 function choose(){stopVoice();setState('choose',['ritual','choices','coin']);title('这一枚，你想许给什么？');$('write').focus({preventScroll:true});}
 function write(){stopVoice();setState('writing',['ritual','writing','back','coin']);title('把心里的愿，写下来。');$('wish').value=wishText;updateInput();$('wish').focus({preventScroll:true});}
 $('write').onclick=write;$('voiceFallback').onclick=write;$('back').onclick=choose;
 function updateInput(){const el=$('wish');if(Array.from(el.value).length>400)el.value=Array.from(el.value).slice(0,400).join('');$('count').textContent=`还可写 ${400-Array.from(el.value).length} 字`;$('keep').disabled=submitting||!el.value.trim();clearTimeout(inputTimer);if(el.value.trim())inputTimer=setTimeout(()=>ripple(innerWidth*.5,innerHeight*.74),550);}
 $('wish').addEventListener('input',updateInput);$('wish').addEventListener('compositionend',updateInput);
 $('wish').onfocus=()=>body.classList.add('editing');$('wish').onblur=()=>body.classList.remove('editing');
 $('writing').onsubmit=e=>{e.preventDefault();if($('wish').value.trim())bindWish($('wish').value.trim());};
 async function bindWish(text,preset=false){if(submitting||!['writing','voice'].includes(state))return;
 submitting=true;$('keep').disabled=true;$('confirmVoice').disabled=true;$('back').disabled=true;$('wishPreset').disabled=true;
 const previous=$('keep').textContent;$('keep').textContent='正在寄出…';
 try{await TempleFlow.submitWish(text,{preset});$('wishPreset').hidden=true;}
 catch(error){notice(error.message);$('wishPreset').hidden=false;return;}
 finally{submitting=false;$('keep').textContent=previous;$('keep').disabled=!$('wish').value.trim();$('confirmVoice').disabled=false;$('back').disabled=false;$('wishPreset').disabled=false;}
stopVoice();wishText=Array.from(text).slice(0,400).join('');setState('binding',['coin']);body.classList.remove('editing');$('wish').blur();steps(2);$('coinCaption').textContent='';const flight=$('wishFlight');flight.textContent=wishText;const coin=$('coin').getBoundingClientRect();const dx=coin.x+coin.width/2-innerWidth*.5,dy=coin.y+coin.height/2-innerHeight*.58;await delay(400);const anim=flight.animate([{transform:'translate(-50%,-50%) scale(1)',opacity:1,filter:'blur(0px)'},{transform:'translate(-50%,-50%) scale(.1)',opacity:1,filter:'blur(2px)',offset:.6},{transform:`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px)) scale(.015)`,opacity:0,filter:'blur(6px)'}],{duration:reduced?100:1800,easing:'cubic-bezier(.5,0,.25,1)',fill:'forwards'});await anim.finished;flight.textContent='';anim.cancel();$('coin').classList.add('charged');tone(1100,1.4);ripple(coin.x+coin.width/2,coin.y+coin.height/2);await delay(650);setState('ready',['ritual','coin','target']);title('愿已寄于此枚。','带着它，投入水中吧。');$('coinCaption').textContent='拖起铜钱，在池水中松手';$('coin').setAttribute('aria-label','拿起铜钱并投向池水，也可点击池中央投币');$('hint').textContent='拖拽投币，或轻点水面。';steps(3);$('target').focus({preventScroll:true});}
 $('coin').onclick=()=>{if(state==='pickup')pick();else if(state==='ready')notice('拖起铜钱，在光圈处松手；也可以轻点池水中央。');};
 $('coin').addEventListener('pointerdown',e=>{if(state!=='ready')return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};$('coin').setPointerCapture(e.pointerId);$('coin').classList.add('dragging');hand('holding');moveHand(e);});
 function moveHand(e){$('hand').style.left=e.clientX+'px';$('hand').style.top=e.clientY+'px';}
 document.addEventListener('pointermove',e=>{moveHand(e);if(e.pointerType==='mouse')body.classList.add('custom-cursor');if(drag&&e.pointerId===drag.id){drag.x=e.clientX;drag.y=e.clientY;if(e.pointerType!=='mouse'){show('flyingCoin');$('flyingCoin').style.left=(e.clientX-38)+'px';$('flyingCoin').style.top=(e.clientY-38)+'px';}}});
 document.addEventListener('pointerleave',()=>body.classList.remove('custom-cursor'));
 document.addEventListener('pointerover',e=>{if(drag)return;hand(state==='ready'&&e.target.closest('#coin')?'holding':'point');});
 function cancelDrag(){drag=null;$('coin').classList.remove('dragging');show('flyingCoin',false);hand();}
 $('coin').addEventListener('pointercancel',cancelDrag);
 $('coin').addEventListener('pointerup',e=>{if(!drag)return;const start={x:drag.x,y:drag.y};cancelDrag();if(e.clientY>innerHeight*.56&&e.clientY<innerHeight*.79&&e.clientX>innerWidth*.14&&e.clientX<innerWidth*.86)toss(start);else notice('把铜钱带到池水中央，再轻轻松手。');});
 $('target').onclick=()=>{const r=$('coin').getBoundingClientRect();toss({x:r.x+r.width/2,y:r.y+r.height/2});};
 async function toss(start){if(state!=='ready')return;setState('casting',[]);hand('closed');steps(4);const x=innerWidth*.5,y=innerHeight*.67,coin=$('flyingCoin');show('flyingCoin');coin.style.left=(start.x-38)+'px';coin.style.top=(start.y-38)+'px';tone(1400,.45);const dx=x-start.x,dy=y-start.y;const anim=coin.animate([{transform:'translate(0,0) scale(1) rotateY(0)'},{transform:`translate(${dx*.5}px,${dy*.5-120}px) scale(.65) rotateY(540deg)`,offset:.48},{transform:`translate(${dx}px,${dy}px) scale(.16) rotateY(1080deg)`,opacity:.8}],{duration:reduced?120:1200,easing:'ease-in',fill:'forwards'});await anim.finished;show('flyingCoin',false);anim.cancel();tone(140,1.2,'sine',.13);ripple(x,y,3);for(let i=0;i<12;i++){const p=document.createElement('i');p.className='droplet';p.style.cssText=`left:${x}px;top:${y}px;--dx:${(Math.random()-.5)*150}px;--dy:${-25-Math.random()*65}px`;$('ripples').append(p);setTimeout(()=>p.remove(),1100);}const petals=$('petals');petals.animate([{transform:'translateX(0)'},{transform:'translateX(24px)'},{transform:'translateX(0)'}],{duration:2000});await delay(1200);wishText='';$('wish').value='';$('transcript').textContent='';await delay(1100);setState('complete',['ending']);$('hint').textContent='愿随流水，心向前行。';$('continue').focus({preventScroll:true});window.dispatchEvent(new CustomEvent('wishing-pool:complete'));}
 function reset(){show('continue');$('ending').querySelector('h2').innerHTML='既已许下，<br>便先往前走吧。';$('ending').querySelector('.ending-small').textContent='愿已入水。';stopVoice();cancelDrag();wishText='';$('wish').value='';$('transcript').textContent='';$('coin').classList.remove('charged');steps(0);setState('arrival',['opening']);$('hint').textContent='风过樱梢，水自无言。';$('approach').focus({preventScroll:true});}
 $('again').onclick=()=>{TempleFlow.reset().catch(error=>notice(error.message));reset();};
 $('wishPreset').onclick=()=>bindWish($('wish').value.trim(),true);
 $('continue').onclick=()=>{const evt=new CustomEvent('wishing-pool:continue',{cancelable:true});if(!window.dispatchEvent(evt))return;setState('departed',['ending']);$('ending').querySelector('h2').textContent='心愿已寄，前路徐行。';$('ending').querySelector('.ending-small').textContent='且听一阵风。';show('continue',false);$('hint').textContent='在这里，安静片刻。';};
 function stopVoice(){voiceEpoch++;clearTimeout(silenceTimer);cancelAnimationFrame(raf);if(recognition){recognition.onend=null;recognition.onerror=null;recognition.onresult=null;try{recognition.abort();}catch{}recognition=null;}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}if(meter){meter.close().catch(()=>{});meter=null;}body.classList.remove('listening');}
 function voiceView(){stopVoice();setState('voice',['ritual','voice','coin']);title('不用说给别人听。','只说给这一池水。');$('transcript').textContent='';$('voiceAction').textContent='开始说';show('voiceAction');show('voiceConfirm',false);$('microphone').disabled=false;$('microphone').setAttribute('aria-label','开始说');}
 $('speak').onclick=voiceView;$('retryVoice').onclick=voiceView;
 async function startVoice(){if(body.classList.contains('listening')){finishVoice();return;}const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API){notice('这个浏览器暂不支持语音识别。可使用 Chrome / Edge，或换成写下来。');return;}stopVoice();const epoch=voiceEpoch;wishText='';$('transcript').textContent='';try{const acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(epoch!==voiceEpoch||state!=='voice'){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;meter=new (window.AudioContext||window.webkitAudioContext)();const analyser=meter.createAnalyser();analyser.fftSize=256;meter.createMediaStreamSource(stream).connect(analyser);const buffer=new Uint8Array(analyser.fftSize);let heard=false,lastLoud=performance.now();function sample(){if(!meter)return;analyser.getByteTimeDomainData(buffer);let sum=0;for(const v of buffer)sum+=((v-128)/128)**2;const volume=Math.sqrt(sum/buffer.length);$('microphone').style.setProperty('--volume',1+Math.min(volume*5,.7));if(volume>.018){heard=true;lastLoud=performance.now();}if(heard&&performance.now()-lastLoud>2000&&wishText.trim()){finishVoice();return;}raf=requestAnimationFrame(sample);}recognition=new API();recognition.lang='zh-CN';recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{wishText=Array.from(Array.from(e.results).map(r=>r[0].transcript).join('')).slice(0,400).join('');$('transcript').textContent=wishText;clearTimeout(silenceTimer);silenceTimer=setTimeout(()=>{if(performance.now()-lastLoud>1900)finishVoice();},2200);ripple(innerWidth*.5,innerHeight*.73);};recognition.onerror=e=>{const messages={'not-allowed':'麦克风权限未开启，可以允许访问后重试，或换成写下来。','network':'语音识别暂时无法连接，请重试或换成写下来。','no-speech':'还没有听清你的愿望，可以再说一次。','audio-capture':'没有找到可用的麦克风，可以换成写下来。'};notice(messages[e.error]||'这次没有听清，请重试或换成写下来。');stopVoice();$('voiceAction').textContent='重新说';};recognition.onend=()=>{if(state==='voice'&&body.classList.contains('listening'))finishVoice();};recognition.start();body.classList.add('listening');title('我在听。','');$('voiceAction').textContent='说完了';$('microphone').setAttribute('aria-label','说完了');sample();}catch(error){if(epoch!==voiceEpoch)return;stopVoice();notice(error.name==='NotAllowedError'?'麦克风权限未开启，可以允许访问后重试，或换成写下来。':'暂时无法使用麦克风，请检查设备或换成写下来。');}}
 function finishVoice(){if(state!=='voice')return;const text=wishText.trim();stopVoice();if(!text){title('还没听清，再说一次好吗？');$('voiceAction').textContent='开始说';return;}wishText=text;title('这是你想寄出的愿吗？');$('transcript').textContent='“'+text+'”';show('voiceAction',false);show('voiceConfirm');$('microphone').disabled=true;$('confirmVoice').focus({preventScroll:true});}
 $('voiceAction').onclick=startVoice;$('microphone').onclick=startVoice;$('confirmVoice').onclick=()=>{if(wishText.trim())bindWish(wishText);};
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&['writing','voice'].includes(state))choose();});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state==='voice'&&body.classList.contains('listening'))finishVoice();if(audio)audio.suspend();}else if(audio&&!muted)audio.resume();});
 window.addEventListener('pagehide',()=>{stopVoice();clearInterval(ambient);});
 for(let i=0;i<20;i++){const el=document.createElement('i');el.className='petal';el.style.cssText=`--x:${Math.random()*100}%;--duration:${15+Math.random()*16}s;--delay:${-Math.random()*30}s`;$('petals').append(el);}
 window.WishingPool={enter:approach,reset,get state(){return state;}};
})();
